// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClCzhN-wISI49_HDAGVSET3TLgQHl2KeE',
    appId: '1:299114969762:web:afcaba321b270f62ed35fb',
    messagingSenderId: '299114969762',
    projectId: 'flutter-pemrograman-web',
    authDomain: 'flutter-pemrograman-web.firebaseapp.com',
    storageBucket: 'flutter-pemrograman-web.appspot.com',
    measurementId: 'G-2DL9MG7VEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_8PZ_BMvEhOoFNTF_1DIEkPwQ30oKdi4',
    appId: '1:299114969762:android:c91acd56a7147e0eed35fb',
    messagingSenderId: '299114969762',
    projectId: 'flutter-pemrograman-web',
    storageBucket: 'flutter-pemrograman-web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu5_uuYe_um4Mi462AH86UBbT8kO3F-M4',
    appId: '1:299114969762:ios:7a53e80f729f9383ed35fb',
    messagingSenderId: '299114969762',
    projectId: 'flutter-pemrograman-web',
    storageBucket: 'flutter-pemrograman-web.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu5_uuYe_um4Mi462AH86UBbT8kO3F-M4',
    appId: '1:299114969762:ios:7a53e80f729f9383ed35fb',
    messagingSenderId: '299114969762',
    projectId: 'flutter-pemrograman-web',
    storageBucket: 'flutter-pemrograman-web.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClCzhN-wISI49_HDAGVSET3TLgQHl2KeE',
    appId: '1:299114969762:web:64c92a2c2fe3dcdded35fb',
    messagingSenderId: '299114969762',
    projectId: 'flutter-pemrograman-web',
    authDomain: 'flutter-pemrograman-web.firebaseapp.com',
    storageBucket: 'flutter-pemrograman-web.appspot.com',
    measurementId: 'G-J2E37MM8J4',
  );
}
